---
title: "Insert Title"
author: "Sheila Damson"

output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    orientation: columns
    vertical_layout: scroll
---

```{r}
library(flexdashboard) 
library(tidyverse)
library(spotifyr)
library(plotly) 
library(Cairo)
library(ggplot2)
library(compmus)
```

Assignment Week 11:
======================================================================

Introduction: {data-width=200}
----------------------------------------------------------------------
For this assignment I have created a graphical description of the Novelty Function and a 
Tempogram for the songs:

1) Data.Matrix (Ryoji Ikeda)

2) Ocelot of Salvation (Immortal Onion)

(Right side: Novelty Function; Left side: Tempogram)


Novelty Function: {data-width=400, .tabset}
----------------------------------------------------------------------

### Song 1:

```{r}
# Data.Matrix

d.m <-
  get_tidy_audio_analysis("5ZmSq1xJbf1IptikZZgvJ6") |>
  select(segments) |>
  unnest(segments)

d.m |>
  mutate(loudness_max_time = start + loudness_max_time) |>
  arrange(loudness_max_time) |>
  mutate(delta_loudness = loudness_max - lag(loudness_max)) |>
  ggplot(aes(x = loudness_max_time, y = pmax(0, delta_loudness))) +
  geom_line() +
  xlim(0, 30) +
  theme_minimal() +
  labs(x = "Time (s)", y = "Novelty")

d.m |>
  mutate(pitches = map(pitches, compmus_normalise, "clr")) |>
  arrange(start) |>
  mutate(pitches = map2(pitches, lag(pitches), `-`)) |>
  slice(-1) |> 
  compmus_gather_chroma() |> 
  group_by(start, duration) |> 
  summarise(novelty = sum(log1p(pmax(value, 0)))) |> 
  ggplot(aes(x = start + duration / 2, y = novelty)) +
  geom_line() +
  xlim(0, 30) +
  theme_minimal() +
  labs(x = "Time (s)", y = "Novelty")

```

### Song 2: 

```{r}
# Ocelot of Salvation

o.o.s <-
  get_tidy_audio_analysis("7D4gttjv3ot3vuc8We5aVE") |>
  select(segments) |>
  unnest(segments)

o.o.s |>
  mutate(loudness_max_time = start + loudness_max_time) |>
  arrange(loudness_max_time) |>
  mutate(delta_loudness = loudness_max - lag(loudness_max)) |>
  ggplot(aes(x = loudness_max_time, y = pmax(0, delta_loudness))) +
  geom_line() +
  xlim(0, 30) +
  theme_minimal() +
  labs(x = "Time (s)", y = "Novelty")

o.o.s |>
  mutate(pitches = map(pitches, compmus_normalise, "clr")) |>
  arrange(start) |>
  mutate(pitches = map2(pitches, lag(pitches), `-`)) |>
  slice(-1) |> 
  compmus_gather_chroma() |> 
  group_by(start, duration) |> 
  summarise(novelty = sum(log1p(pmax(value, 0)))) |> 
  ggplot(aes(x = start + duration / 2, y = novelty)) +
  geom_line() +
  xlim(0, 30) +
  theme_minimal() +
  labs(x = "Time (s)", y = "Novelty")

```

Tempogram: {data-width=400, .tapset}
=========================================================================

### Song 1:

```{r}

kaka <- get_tidy_audio_analysis("5ZmSq1xJbf1IptikZZgvJ6")


kaka |>
  tempogram(window_size = 8, hop_size = 10, cyclic = FALSE) |>
  ggplot(aes(x = time, y = bpm, fill = power)) +
  geom_raster() +
  scale_fill_viridis_c(guide = "none") +
  labs(x = "Time (s)", y = "Tempo (BPM)") +
  theme_classic()

```

### Song 2:

```{r}

kaka2 <- get_tidy_audio_analysis("7D4gttjv3ot3vuc8We5aVE")


kaka2 |>
  tempogram(window_size = 8, hop_size = 1, cyclic = FALSE) |>
  ggplot(aes(x = time, y = bpm, fill = power)) +
  geom_raster() +
  scale_fill_viridis_c(guide = "none") +
  labs(x = "Time (s)", y = "Tempo (BPM)") +
  theme_classic()
```





Week 10:
======================================================================

Information {data-width=250}
----------------------------------------------------------------------
Here you can find the Chordograms of the songs:

Song 1: Ocelot of Salvation (Immortal Onion)

Song 2: Data.Matrix (Ryoji Ikeda)

Song 3: Neray Neray Vas (Soch the Band)


The other taps are representing the Track-Level Summaries Of the playlists of my friends: Anett, Io, Lorah.

Disclaimer: I see that some parts of my Assignment are missing after knitting the file. I did not have time to figure out why so I guess this is what I have hehe


Chordograms {data-width=750, .tabset}
----------------------------------------------------------------------

### Song 1:

```{r}
circshift <- function(v, n) {
  if (n == 0) v else c(tail(v, n), head(v, -n))
}

#      C     C#    D     Eb    E     F     F#    G     Ab    A     Bb    B
major_chord <-
  c(   1,    0,    0,    0,    1,    0,    0,    1,    0,    0,    0,    0)
minor_chord <-
  c(   1,    0,    0,    1,    0,    0,    0,    1,    0,    0,    0,    0)
seventh_chord <-
  c(   1,    0,    0,    0,    1,    0,    0,    1,    0,    0,    1,    0)

major_key <-
  c(6.35, 2.23, 3.48, 2.33, 4.38, 4.09, 2.52, 5.19, 2.39, 3.66, 2.29, 2.88)
minor_key <-
  c(6.33, 2.68, 3.52, 5.38, 2.60, 3.53, 2.54, 4.75, 3.98, 2.69, 3.34, 3.17)

chord_templates <-
  tribble(
    ~name, ~template,
    "Gb:7", circshift(seventh_chord, 6),
    "Gb:maj", circshift(major_chord, 6),
    "Bb:min", circshift(minor_chord, 10),
    "Db:maj", circshift(major_chord, 1),
    "F:min", circshift(minor_chord, 5),
    "Ab:7", circshift(seventh_chord, 8),
    "Ab:maj", circshift(major_chord, 8),
    "C:min", circshift(minor_chord, 0),
    "Eb:7", circshift(seventh_chord, 3),
    "Eb:maj", circshift(major_chord, 3),
    "G:min", circshift(minor_chord, 7),
    "Bb:7", circshift(seventh_chord, 10),
    "Bb:maj", circshift(major_chord, 10),
    "D:min", circshift(minor_chord, 2),
    "F:7", circshift(seventh_chord, 5),
    "F:maj", circshift(major_chord, 5),
    "A:min", circshift(minor_chord, 9),
    "C:7", circshift(seventh_chord, 0),
    "C:maj", circshift(major_chord, 0),
    "E:min", circshift(minor_chord, 4),
    "G:7", circshift(seventh_chord, 7),
    "G:maj", circshift(major_chord, 7),
    "B:min", circshift(minor_chord, 11),
    "D:7", circshift(seventh_chord, 2),
    "D:maj", circshift(major_chord, 2),
    "F#:min", circshift(minor_chord, 6),
    "A:7", circshift(seventh_chord, 9),
    "A:maj", circshift(major_chord, 9),
    "C#:min", circshift(minor_chord, 1),
    "E:7", circshift(seventh_chord, 4),
    "E:maj", circshift(major_chord, 4),
    "G#:min", circshift(minor_chord, 8),
    "B:7", circshift(seventh_chord, 11),
    "B:maj", circshift(major_chord, 11),
    "D#:min", circshift(minor_chord, 3)
  )

key_templates <-
  tribble(
    ~name, ~template,
    "Gb:maj", circshift(major_key, 6),
    "Bb:min", circshift(minor_key, 10),
    "Db:maj", circshift(major_key, 1),
    "F:min", circshift(minor_key, 5),
    "Ab:maj", circshift(major_key, 8),
    "C:min", circshift(minor_key, 0),
    "Eb:maj", circshift(major_key, 3),
    "G:min", circshift(minor_key, 7),
    "Bb:maj", circshift(major_key, 10),
    "D:min", circshift(minor_key, 2),
    "F:maj", circshift(major_key, 5),
    "A:min", circshift(minor_key, 9),
    "C:maj", circshift(major_key, 0),
    "E:min", circshift(minor_key, 4),
    "G:maj", circshift(major_key, 7),
    "B:min", circshift(minor_key, 11),
    "D:maj", circshift(major_key, 2),
    "F#:min", circshift(minor_key, 6),
    "A:maj", circshift(major_key, 9),
    "C#:min", circshift(minor_key, 1),
    "E:maj", circshift(major_key, 4),
    "G#:min", circshift(minor_key, 8),
    "B:maj", circshift(major_key, 11),
    "D#:min", circshift(minor_key, 3)
  )
```

```{r}
ocelot <-
  get_tidy_audio_analysis("7D4gttjv3ot3vuc8We5aVE") |>
  compmus_align(sections, segments) |>
  select(sections) |>
  unnest(sections) |>
  mutate(
    pitches =
      map(segments,
        compmus_summarise, pitches,
        method = "mean", norm = "manhattan"
      )
  )

ocelot |> 
  compmus_match_pitch_template(
    key_templates,         # Change to chord_templates if descired
    method = "euclidean",  # Try different distance metrics
    norm = "manhattan"     # Try different norms
  ) |>
  ggplot(
    aes(x = start + duration / 2, width = duration, y = name, fill = d)
  ) +
  geom_tile() +
  scale_fill_viridis_c(guide = "none") +
  theme_minimal() +
  labs(x = "Time (s)", y = "")
```

### Song 2:

```{r}
data.m <-
  get_tidy_audio_analysis("5ZmSq1xJbf1IptikZZgvJ6") |>
  compmus_align(sections, segments) |>
  select(sections) |>
  unnest(sections) |>
  mutate(
    pitches =
      map(segments,
        compmus_summarise, pitches,
        method = "mean", norm = "manhattan"
      )
  )

data.m |> 
  compmus_match_pitch_template(
    key_templates,         # Change to chord_templates if descired
    method = "euclidean",  # Try different distance metrics
    norm = "manhattan"     # Try different norms
  ) |>
  ggplot(
    aes(x = start + duration / 2, width = duration, y = name, fill = d)
  ) +
  geom_tile() +
  scale_fill_viridis_c(guide = "none") +
  theme_minimal() +
  labs(x = "Time (s)", y = "")
```
### Song 3:

```{r}
# spotify:track:5P9gtOtId7RoyakIvlPGwM

soch <-
  get_tidy_audio_analysis("5P9gtOtId7RoyakIvlPGwM") |>
  compmus_align(sections, segments) |>
  select(sections) |>
  unnest(sections) |>
  mutate(
    pitches =
      map(segments,
        compmus_summarise, pitches,
        method = "mean", norm = "manhattan"
      )
  )

soch |> 
  compmus_match_pitch_template(
    key_templates,         # Change to chord_templates if descired
    method = "euclidean",  # Try different distance metrics
    norm = "manhattan"     # Try different norms
  ) |>
  ggplot(
    aes(x = start + duration / 2, width = duration, y = name, fill = d)
  ) +
  geom_tile() +
  scale_fill_viridis_c(guide = "none") +
  theme_minimal() +
  labs(x = "Time (s)", y = "")

```
### Friends:

```{r}
Anett <-
  get_playlist_audio_features(
    "",
    "37i9dQZF1Fa70zA0LneCPK"
  ) |>
  slice(1:30) |>
  add_audio_analysis()
Io <-
  get_playlist_audio_features(
    "",
    "37i9dQZF1Fa3SuuqxqBxeG"
  ) |>
  slice(1:30) |>
  add_audio_analysis()
Lorah <-
  get_playlist_audio_features(
    "",
    "37i9dQZF1FamLjwP9lNgqU"
  ) |>
  slice(1:30) |>
  add_audio_analysis()
f <-
  Anett |>
  mutate(genre = "Anett") |>
  bind_rows(Io |> mutate(genre = "Io")) |>
  bind_rows(Lorah |> mutate(genre = "Lorah"))


f |>
  mutate(
    sections =
      map(
        sections,                                    # sections or segments
        summarise_at,
        vars(tempo, loudness, duration),             # features of interest
        list(section_mean = mean, section_sd = sd)   # aggregation functions
      )
  ) |>
  unnest(sections) |>
  ggplot(
    aes(
      x = tempo,
      y = tempo_section_sd,
      colour = genre,
      alpha = loudness
    )
  ) +
  geom_point(aes(size = duration / 60)) +
  geom_rug() +
  theme_minimal() +
  ylim(0, 5) +
  labs(
    x = "Mean Tempo (bpm)",
    y = "SD Tempo",
    colour = "Genre",
    size = "Duration (min)",
    alpha = "Volume (dBFS)"
  )
```

### Timbre Features:

```{r}
f |>
  mutate(
    timbre =
      map(
        segments,
        compmus_summarise,
        timbre,
        method = "mean"
      )
  ) |>
  select(genre, timbre) |>
  compmus_gather_timbre() |>
  ggplot(aes(x = basis, y = value, fill = genre)) +
  geom_violin() +
  scale_fill_viridis_d() +
  labs(x = "Spotify Timbre Coefficients", y = "", fill = "Genre")
```


Week 9:
======================================================================

Descriptive {data-width=250}
----------------------------------------------------------------------

Dear person to Peer review this page,
version for each Cepstrogram and Self-Similarity Matrix. I focused more on the layout of the page this week. It is not that great yet... But I will get there eventually.

Song 1: Ocelot of Salvation (Immortal Onion)

This song is a sudion Jazz song by a polish band. I chose the live version of this song because I liket it more than the sudio recorded version.  

Song 2:

Data.Matrix 

Song 3:

"insert title"

Cepstrogram {data-width=375, .tabset}
----------------------------------------------------------------------

### Song 1:

```{r}

# Course Lecture 3:


#spotify:track:7D4gttjv3ot3vuc8We5aVE

# Ocelot of Salvation

oos2 <-
  get_tidy_audio_analysis("7D4gttjv3ot3vuc8We5aVE") |> # Change URI.
  compmus_align(bars, segments) |>                     # Change `bars`
  select(bars) |>                                      #   in all three
  unnest(bars) |>                                      #   of these lines.
  mutate(
    pitches =
      map(segments,
        compmus_summarise, pitches,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  ) |>
  mutate(
    timbre =
      map(segments,
        compmus_summarise, timbre,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  )


# 2)

oos2 |>
  compmus_gather_timbre() |>
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = basis,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  scale_fill_viridis_c() +                              
  theme_classic()

# 3)

oos2 |>
  compmus_self_similarity(timbre, "cosine") |> 
  ggplot(
    aes(
      x = xstart + xduration / 2,
      width = xduration,
      y = ystart + yduration / 2,
      height = yduration,
      fill = d
    )
  ) +
  geom_tile() +
  coord_fixed() +
  scale_fill_viridis_c(guide = "none") +
  theme_classic() +
  labs(x = "", y = "")

```


### Song 2:


```{r}
# Data.Matrix spotify:track:5ZmSq1xJbf1IptikZZgvJ6

dm <- get_track_audio_features("5ZmSq1xJbf1IptikZZgvJ6")

dm <-
  get_tidy_audio_analysis("5ZmSq1xJbf1IptikZZgvJ6") |> # Change URI.
  compmus_align(bars, segments) |>                     # Change `bars`
  select(bars) |>                                      #   in all three
  unnest(bars) |>                                      #   of these lines.
  mutate(
    pitches =
      map(segments,
        compmus_summarise, pitches,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  ) |>
  mutate(
    timbre =
      map(segments,
        compmus_summarise, timbre,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  )


# 2)

dm |>
  compmus_gather_timbre() |>
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = basis,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  scale_fill_viridis_c() +                              
  theme_classic()

# 3)

dm |>
  compmus_self_similarity(timbre, "cosine") |> 
  ggplot(
    aes(
      x = xstart + xduration / 2,
      width = xduration,
      y = ystart + yduration / 2,
      height = yduration,
      fill = d
    )
  ) +
  geom_tile() +
  coord_fixed() +
  scale_fill_viridis_c(guide = "none") +
  theme_classic() +
  labs(x = "", y = "")

```

### Song 3:

```{r}

# spotify:track:0pajODU8W5ucIXvkJ4FXWG, Pawel's song

pawel <- get_track_audio_features("0pajODU8W5ucIXvkJ4FXWG")

pawel <-
  get_tidy_audio_analysis("0pajODU8W5ucIXvkJ4FXWG") |> # Change URI.
  compmus_align(bars, segments) |>                     # Change `bars`
  select(bars) |>                                      #   in all three
  unnest(bars) |>                                      #   of these lines.
  mutate(
    pitches =
      map(segments,
        compmus_summarise, pitches,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  ) |>
  mutate(
    timbre =
      map(segments,
        compmus_summarise, timbre,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  )


# 2)

pawel |>
  compmus_gather_timbre() |>
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = basis,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  scale_fill_viridis_c() +                              
  theme_classic()

# 3)

pawel |>
  compmus_self_similarity(timbre, "cosine") |> 
  ggplot(
    aes(
      x = xstart + xduration / 2,
      width = xduration,
      y = ystart + yduration / 2,
      height = yduration,
      fill = d
    )
  ) +
  geom_tile() +
  coord_fixed() +
  scale_fill_viridis_c(guide = "none") +
  theme_classic() +
  labs(x = "", y = "")



```

Week 7
=====================================================================


### Lecture 1

```{r}
anett <- get_playlist_audio_features("", "37i9dQZF1Fa70zA0LneCPK") #<spotify:playlist:37i9dQZF1Fa70zA0LneCPK>

lorah <- get_playlist_audio_features("", "37i9dQZF1FamLjwP9lNgqU") #<spotify:playlist:37i9dQZF1FamLjwP9lNgqU>

io <- get_playlist_audio_features("", "37i9dQZF1Fa3SuuqxqBxeG") #<spotify:playlist:37i9dQZF1Fa3SuuqxqBxeG>



friends <- bind_rows( lorah |> mutate(category = "Lorah"), anett |> mutate(category = "Anett"), io |> mutate(category = "Io") )

```

Column
-----------------------------------------------------------------------

### First Friend's graphs:

```{r}

anett |> ggplot(aes(x = danceability, y = energy, size = loudness, color = mode)) + geom_point()

friends |> ggplot(aes(x = category, y = energy)) + geom_boxplot()

friends |> ggplot(aes(x = category, y = energy)) + geom_violin()

friends |> ggplot(aes(x = danceability, y = energy, size = loudness, color = category)) + geom_point()


```

Week 8
==========================================================================


Column
---------------------------------------------------------------------------


### Lecture 2:

```{r}
# Week Lecture 2:

oos0 <- get_track_audio_features("7D4gttjv3ot3vuc8We5aVE")

oos1 <-
  get_tidy_audio_analysis("7D4gttjv3ot3vuc8We5aVE") |>
  select(segments) |>
  unnest(segments) |>
  select(start, duration, pitches)

# 2)

oos1 |>
  mutate(pitches = map(pitches, compmus_normalise, "euclidean")) |>
  compmus_gather_chroma() |> 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c()
```




